### ISSUE TITLE
Android> General: Local Database

### ISSUE THREAD

**Issue by aolite** [NemeumProject/Nemeum#127]
Establish a local database to store some data related to scenarios, event, etc. 

The main of this is to enable navigation through the APP.

**Comment by aolite** [comment]
There is a new requirement regarding flow change in the app..

**Comment by antony11995** [comment]
![java structure local database](https://user-images.githubusercontent.com/23583721/49971782-a4364080-fefd-11e8-978b-9d510aea6ded.JPG)
![scenarios local database](https://user-images.githubusercontent.com/23583721/49971783-a4364080-fefd-11e8-990b-40a05378e29d.JPG)

**Comment by antony11995** [comment]
Java class with the structure completed, Now looking the way to establish the connection and also converting the  data types to SQLite syntax.

**Comment by antony11995** [comment]
![utilities](https://user-images.githubusercontent.com/23583721/50036659-6e19bf00-ffd8-11e8-8eb7-1a83b436adf1.JPG)

**Comment by antony11995** [comment]
Changing the flow of the app, we need that always the data to show to the user about scenarios will be gotten from locale storage, to do this, @cpereirarafa I need your support and also from @aexposito6. I need the webservice to be fill out the local SQLite Database, and after that @cpereirarafa should read and show the scenarios information from the database.
