### ISSUE TITLE
[Templates] Daily Meeting Templates

### ISSUE THREAD

**Issue by aolite** [NemeumProject/Nemeum#49]
It is compulsory to follow up the presented daily meeting templates.  Please consider their use within the next sprint.

**Comment by antony11995** [comment]
Hi @aolite,

Please find enclosed a template designed for Daily Meeting Minutes to use in the second Sprint.
Please, let us know if do you agree and then we can close this Bug.
Thank you!.
Antony M. 
[Daily_Meeting_Minutes.pdf](https://github.com/NemeumProject/Nemeum/files/2548196/Daily_Meeting_Minutes.pdf)
